# Site settings
name: Wang Zhikai's blog
email: 2568441388@qq.com
author: 王志凯
url: https://w-40.github.io/
resume_site: https://w-40.github.io/
github: https://github.com/w-40
baseurl: ""
description: 中北大学软件学院的一名小渣渣
meta_description: 王志凯;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: w-40

# Build settings
markdown: kramdown

baidu_analysis: c194e0021d0babc93cd1cef1d94b1134

